modLoader="javafml"
loaderVersion="[47,)"
license="LGPLv3"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Trhod177s"
description='''Adds loot bags that drop from mobs and dungeon chests. Use a loot bag to receive random loot.'''
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"
